name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build.yml
      - cmd/**/*.go
      - makefile
      - go.mod
      - go.sum

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: Open-CMSIS-Pack/workflows-and-actions-collection/.github/workflows/build-and-verify.yml@build-verify-workflow
    with:
      program: cpackget
      build-matrix-goos: '["windows", "linux", "darwin"]'
      build-matrix-arch: '["amd64", "arm64"]'
      test-platform: '["ubuntu-24.04", "windows-2022", "macos-14"]'
      test-arch: '["amd64", "arm64"]'
      go-version-file: ./go.mod
      artifact-retention-days: 1
