name: Release

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/release.yml
      - ./scripts/release_notes
      - .goreleaser.yml
  push:
    tags:
      - "v*"

jobs:
  test:
    uses: Open-CMSIS-Pack/cpackget/.github/workflows/test.yml@main

  goreleaser:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          pattern: test-results-*
          path: testreport/

      - name: Zip test reports
        run: |
          zip -r testreport.zip testreport

      - name: Attach test reports to release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: testreport.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Generate release notes
        run: |
          ./scripts/release_notes > /tmp/RELEASE_NOTES

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release ${{ github.event_name != 'push' && '--snapshot' || '' }} --clean --release-notes=/tmp/RELEASE_NOTES
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
